{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mirrgieriana.xarpite",
    "module": "xarpeg-kotlin-peg-parser",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "xarpeg-kotlin-peg-parser-metadata-3.0.0.jar",
          "url": "xarpeg-kotlin-peg-parser-3.0.0.jar",
          "size": 25271,
          "sha512": "0e50223e42901038542a84ef64f33f8fba2a4054bc8faf21e5727fda73fb8f86c0c5be22845a80487dcd04bb9a4dc0fe49cad98716f157d28ca13c8f00c5752d",
          "sha256": "64577c8c08b3c4b971717045d13108dc93303017dbcc921e88adf1946a2b47f5",
          "sha1": "691352be11549d9224d2c05fcd581040c49e2b3c",
          "md5": "04ce05adbe8d79b9ec9e544222053683"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "xarpeg-kotlin-peg-parser-kotlin-3.0.0-sources.jar",
          "url": "xarpeg-kotlin-peg-parser-3.0.0-sources.jar",
          "size": 19658,
          "sha512": "e195b468fbba3fccbb7ddf16b7b2f1fce3b17f1b4f86538db9e13f3fca7ca45e764e2c8de605ebc1ddc068df9d7cc263829fd122645c1fb52f7c37196243e643",
          "sha256": "65a6c1cf1e248581d54dc9c4d9a72cd362d205dc9a392bad8bb2a3b8b397d5c3",
          "sha1": "32786c0bc5a802cbcc1f025c2f0e97169206c55c",
          "md5": "67fdb2e46f30d605d202f6e46a503c29"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../xarpeg-kotlin-peg-parser-js/3.0.0/xarpeg-kotlin-peg-parser-js-3.0.0.module",
        "group": "io.github.mirrgieriana.xarpite",
        "module": "xarpeg-kotlin-peg-parser-js",
        "version": "3.0.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../xarpeg-kotlin-peg-parser-js/3.0.0/xarpeg-kotlin-peg-parser-js-3.0.0.module",
        "group": "io.github.mirrgieriana.xarpite",
        "module": "xarpeg-kotlin-peg-parser-js",
        "version": "3.0.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../xarpeg-kotlin-peg-parser-js/3.0.0/xarpeg-kotlin-peg-parser-js-3.0.0.module",
        "group": "io.github.mirrgieriana.xarpite",
        "module": "xarpeg-kotlin-peg-parser-js",
        "version": "3.0.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../xarpeg-kotlin-peg-parser-jvm/3.0.0/xarpeg-kotlin-peg-parser-jvm-3.0.0.module",
        "group": "io.github.mirrgieriana.xarpite",
        "module": "xarpeg-kotlin-peg-parser-jvm",
        "version": "3.0.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../xarpeg-kotlin-peg-parser-jvm/3.0.0/xarpeg-kotlin-peg-parser-jvm-3.0.0.module",
        "group": "io.github.mirrgieriana.xarpite",
        "module": "xarpeg-kotlin-peg-parser-jvm",
        "version": "3.0.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../xarpeg-kotlin-peg-parser-jvm/3.0.0/xarpeg-kotlin-peg-parser-jvm-3.0.0.module",
        "group": "io.github.mirrgieriana.xarpite",
        "module": "xarpeg-kotlin-peg-parser-jvm",
        "version": "3.0.0"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../xarpeg-kotlin-peg-parser-linuxarm64/3.0.0/xarpeg-kotlin-peg-parser-linuxarm64-3.0.0.module",
        "group": "io.github.mirrgieriana.xarpite",
        "module": "xarpeg-kotlin-peg-parser-linuxarm64",
        "version": "3.0.0"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../xarpeg-kotlin-peg-parser-linuxarm64/3.0.0/xarpeg-kotlin-peg-parser-linuxarm64-3.0.0.module",
        "group": "io.github.mirrgieriana.xarpite",
        "module": "xarpeg-kotlin-peg-parser-linuxarm64",
        "version": "3.0.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../xarpeg-kotlin-peg-parser-linuxx64/3.0.0/xarpeg-kotlin-peg-parser-linuxx64-3.0.0.module",
        "group": "io.github.mirrgieriana.xarpite",
        "module": "xarpeg-kotlin-peg-parser-linuxx64",
        "version": "3.0.0"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../xarpeg-kotlin-peg-parser-linuxx64/3.0.0/xarpeg-kotlin-peg-parser-linuxx64-3.0.0.module",
        "group": "io.github.mirrgieriana.xarpite",
        "module": "xarpeg-kotlin-peg-parser-linuxx64",
        "version": "3.0.0"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../xarpeg-kotlin-peg-parser-mingwx64/3.0.0/xarpeg-kotlin-peg-parser-mingwx64-3.0.0.module",
        "group": "io.github.mirrgieriana.xarpite",
        "module": "xarpeg-kotlin-peg-parser-mingwx64",
        "version": "3.0.0"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../xarpeg-kotlin-peg-parser-mingwx64/3.0.0/xarpeg-kotlin-peg-parser-mingwx64-3.0.0.module",
        "group": "io.github.mirrgieriana.xarpite",
        "module": "xarpeg-kotlin-peg-parser-mingwx64",
        "version": "3.0.0"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../xarpeg-kotlin-peg-parser-wasm-js/3.0.0/xarpeg-kotlin-peg-parser-wasm-js-3.0.0.module",
        "group": "io.github.mirrgieriana.xarpite",
        "module": "xarpeg-kotlin-peg-parser-wasm-js",
        "version": "3.0.0"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../xarpeg-kotlin-peg-parser-wasm-js/3.0.0/xarpeg-kotlin-peg-parser-wasm-js-3.0.0.module",
        "group": "io.github.mirrgieriana.xarpite",
        "module": "xarpeg-kotlin-peg-parser-wasm-js",
        "version": "3.0.0"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../xarpeg-kotlin-peg-parser-wasm-js/3.0.0/xarpeg-kotlin-peg-parser-wasm-js-3.0.0.module",
        "group": "io.github.mirrgieriana.xarpite",
        "module": "xarpeg-kotlin-peg-parser-wasm-js",
        "version": "3.0.0"
      }
    }
  ]
}
