{
  "formatVersion": "1.1",
  "component": {
    "url": "../../xarpeg-kotlinMultiplatform/4.0.3/xarpeg-kotlinMultiplatform-4.0.3.module",
    "group": "io.github.mirrgieriana",
    "module": "xarpeg-kotlinMultiplatform",
    "version": "4.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "xarpeg-kotlin-peg-parser-wasm-js-4.0.3.klib",
          "url": "xarpeg-wasmJs-4.0.3.klib",
          "size": 203673,
          "sha512": "5ab0fdbd93cbfdc488841cfaf4b11c704976b6eac6629d10df21b2f7a28dd0ef852a819fdf2c69ae5bba9b00d6481ade7911c222bb7938d906a040e357cd3cde",
          "sha256": "40f8f4bd30dfb7e77cd836985193aa587583cb32faf5a27b1d423a35ede4b7a0",
          "sha1": "5a034b763cba4662ac75c862ec656976610ffcfa",
          "md5": "94c88321c4ea6ec3253cb7bb8f4c189c"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "xarpeg-kotlin-peg-parser-wasm-js-4.0.3.klib",
          "url": "xarpeg-wasmJs-4.0.3.klib",
          "size": 203673,
          "sha512": "5ab0fdbd93cbfdc488841cfaf4b11c704976b6eac6629d10df21b2f7a28dd0ef852a819fdf2c69ae5bba9b00d6481ade7911c222bb7938d906a040e357cd3cde",
          "sha256": "40f8f4bd30dfb7e77cd836985193aa587583cb32faf5a27b1d423a35ede4b7a0",
          "sha1": "5a034b763cba4662ac75c862ec656976610ffcfa",
          "md5": "94c88321c4ea6ec3253cb7bb8f4c189c"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "xarpeg-kotlin-peg-parser-wasm-js-4.0.3-sources.jar",
          "url": "xarpeg-wasmJs-4.0.3-sources.jar",
          "size": 20087,
          "sha512": "b5e2efff2086d87e5f56641d094bc6b33547b614a7498216178a996c44fe75838e153797b4e97b12344a1fa5a38c1da3ee194236a6f5fdfdf22c859f9c0ba17d",
          "sha256": "f297d90f415924e412edf669984ac316c646469eb96c41c07f81cc585b0643e8",
          "sha1": "fc7ecff7ef6575503847a6504e7843079f0e9c69",
          "md5": "6a3472f55413e03aceec28d17eb075d2"
        }
      ]
    }
  ]
}
