{
  "formatVersion": "1.1",
  "component": {
    "url": "../../xarpeg-kotlin-peg-parser/3.0.0/xarpeg-kotlin-peg-parser-3.0.0.module",
    "group": "io.github.mirrgieriana.xarpite",
    "module": "xarpeg-kotlin-peg-parser",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "xarpeg-kotlin-peg-parser-mingwX64Main-3.0.0.klib",
          "url": "xarpeg-kotlin-peg-parser-mingwx64-3.0.0.klib",
          "size": 202353,
          "sha512": "09215f2798baeb6e9c9db106325978a91d9543331e888627457225dbd84e5f8c761d1c9f8ea9f86b0208f150fd5fdd12296662911a142c693af441e2a34f2f0e",
          "sha256": "51eed6bbe12d7513b2d731f46f78efe9a13e9994ff87aee5d978e7fed269cfe2",
          "sha1": "5e6539aab0709a8e239f10f49bd09afac722e53c",
          "md5": "91acda559478ae218c9aa03608534d7c"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "xarpeg-kotlin-peg-parser-mingwx64-3.0.0-sources.jar",
          "url": "xarpeg-kotlin-peg-parser-mingwx64-3.0.0-sources.jar",
          "size": 19658,
          "sha512": "f91a2184e5cecb2e5f204e275b2ed8032a361e19023e261e28eb9a01e5c59d7bb84d5cccc1af6190ec36537103162cf17509f7f3070b6a44be4ac829ee96543e",
          "sha256": "206d751dda36b2bbcd4c6ca0b750d61dbbe09705d93efd060761fe8132b5400a",
          "sha1": "149b5e86a24609641711cd55beaba0947e5d2952",
          "md5": "63d1733c0cd892ff2733ee97921932fe"
        }
      ]
    }
  ]
}
