{
  "formatVersion": "1.1",
  "component": {
    "url": "../../xarpeg-kotlin-peg-parser/3.0.0/xarpeg-kotlin-peg-parser-3.0.0.module",
    "group": "io.github.mirrgieriana.xarpite",
    "module": "xarpeg-kotlin-peg-parser",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "xarpeg-kotlin-peg-parser-jvm-3.0.0.jar",
          "url": "xarpeg-kotlin-peg-parser-jvm-3.0.0.jar",
          "size": 124427,
          "sha512": "7539e271bc45a253a3aa3a41ee12fd8a697b66714a86cd2b8264e17fff1b646423a74fa2c0688c57ffcc31b678baf72923d7e34a54f2b58ce1bb38ec6c4f5cba",
          "sha256": "65b0be550d22d9f9b2f65410f75c4b041818769b4b46307653f9c9801a375658",
          "sha1": "e92edf6372758797a2752587dc74cba6ab7c9ead",
          "md5": "225451f0938ccd3ba598161bdb7fd59d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "xarpeg-kotlin-peg-parser-jvm-3.0.0.jar",
          "url": "xarpeg-kotlin-peg-parser-jvm-3.0.0.jar",
          "size": 124427,
          "sha512": "7539e271bc45a253a3aa3a41ee12fd8a697b66714a86cd2b8264e17fff1b646423a74fa2c0688c57ffcc31b678baf72923d7e34a54f2b58ce1bb38ec6c4f5cba",
          "sha256": "65b0be550d22d9f9b2f65410f75c4b041818769b4b46307653f9c9801a375658",
          "sha1": "e92edf6372758797a2752587dc74cba6ab7c9ead",
          "md5": "225451f0938ccd3ba598161bdb7fd59d"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xarpeg-kotlin-peg-parser-jvm-3.0.0-sources.jar",
          "url": "xarpeg-kotlin-peg-parser-jvm-3.0.0-sources.jar",
          "size": 19616,
          "sha512": "17469649a620aaae7730027199ba0e0c574868e06dd962e7059d18c8c1fd30422b379846ae3994a4f75122989ee1de10e9c2b60644347b9e1f48d715a42728d3",
          "sha256": "5606702e929c99eb650c1d7baf56f131aefca75fe87b573a3571036cd6af11cb",
          "sha1": "7bd14b484e50db638c7215a6e1d253a5c32973f0",
          "md5": "081ba3b38eb4e057c9cbb85646fe6d75"
        }
      ]
    }
  ]
}
