{
  "formatVersion": "1.1",
  "component": {
    "url": "../../xarpeg-kotlin-peg-parser/3.0.0/xarpeg-kotlin-peg-parser-3.0.0.module",
    "group": "io.github.mirrgieriana.xarpite",
    "module": "xarpeg-kotlin-peg-parser",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "xarpeg-kotlin-peg-parser-js-3.0.0.klib",
          "url": "xarpeg-kotlin-peg-parser-js-3.0.0.klib",
          "size": 201663,
          "sha512": "6d44434438bea603d0705059a699242e3322805f5e897ceb14be86bf6548c7cf23a2997fe8978d5a07b5afe42acbc60023726145381e7ec045000bbe0367118e",
          "sha256": "6f1497c881d7cd9ed5f3333af6045f87de5989dd672b7e3e392c2a43b9baad0e",
          "sha1": "89a4a7e59342e6cd4694bf67af5b2cb48b8fe071",
          "md5": "8c5828185f004c68523214d4853677b8"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "xarpeg-kotlin-peg-parser-js-3.0.0.klib",
          "url": "xarpeg-kotlin-peg-parser-js-3.0.0.klib",
          "size": 201663,
          "sha512": "6d44434438bea603d0705059a699242e3322805f5e897ceb14be86bf6548c7cf23a2997fe8978d5a07b5afe42acbc60023726145381e7ec045000bbe0367118e",
          "sha256": "6f1497c881d7cd9ed5f3333af6045f87de5989dd672b7e3e392c2a43b9baad0e",
          "sha1": "89a4a7e59342e6cd4694bf67af5b2cb48b8fe071",
          "md5": "8c5828185f004c68523214d4853677b8"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "xarpeg-kotlin-peg-parser-js-3.0.0-sources.jar",
          "url": "xarpeg-kotlin-peg-parser-js-3.0.0-sources.jar",
          "size": 19602,
          "sha512": "65ed24d0207e3a852652d0dd60a042947d59adc43760ae04406e9203858ac4db58ba2e2fe9a0fd8cc6b6f894c425263358a348b7fe4d4720617493247928475a",
          "sha256": "8630f889342fe1c450592bad19259ef031d44a762ec2eb4303d2525ca4dc3c04",
          "sha1": "9152d8c6b27a0528a658ba18acd4c903dffd053f",
          "md5": "293a3bd6a37fdbaca7bf3b00190aee63"
        }
      ]
    }
  ]
}
