{
  "formatVersion": "1.1",
  "component": {
    "url": "../../xarpeg/5.0.0/xarpeg-5.0.0.module",
    "group": "io.github.mirrgieriana",
    "module": "xarpeg",
    "version": "5.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "xarpeg-linuxArm64Main-5.0.0.klib",
          "url": "xarpeg-linuxarm64-5.0.0.klib",
          "size": 202355,
          "sha512": "1bc4579c91e5366f9b9db3141de694ebd508db7e5680a474e59c3e0d0777d09019955f3f97c77b0074aa70fbb95d0b934ff465c421cb903f775c1c375dd6e1fd",
          "sha256": "8663f2bd62ba0289349443fa19934964844d8ef91b501f0c7e6fc22c9222689d",
          "sha1": "2b9c15612df691118608af0ed7481f36d6d5fa68",
          "md5": "a405d04784bec077aaa667f33f484b84"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "xarpeg-linuxarm64-5.0.0-sources.jar",
          "url": "xarpeg-linuxarm64-5.0.0-sources.jar",
          "size": 19145,
          "sha512": "5be88890f548e647ead35b1b3f65100e212b49b47105ea18ca96c49c826d7c920f81e7e7f9af0c3d0cbc2430b050d758e0d0b736074f211c47f4f53cce6096d2",
          "sha256": "f6745cc1c1b1b61d5e32dfa5cdfeee967eb451cc11fb824d9fb3245331e154c9",
          "sha1": "b4a6d89c1a9dc825c5bc15ac3198d37b4073e2fc",
          "md5": "b194fa6cf86b34f6326593bdb342ad2d"
        }
      ]
    }
  ]
}
