{
  "formatVersion": "1.1",
  "component": {
    "url": "../../xarpeg-kotlin-peg-parser/2.1.0/xarpeg-kotlin-peg-parser-2.1.0.module",
    "group": "io.github.mirrgieriana.xarpite",
    "module": "xarpeg-kotlin-peg-parser",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "xarpeg-kotlin-peg-parser-mingwX64Main-2.1.0.klib",
          "url": "xarpeg-kotlin-peg-parser-mingwx64-2.1.0.klib",
          "size": 192153,
          "sha512": "34133e871a490e8af6fbf26c65c3e91e220e6785a4366cd79d18aba405a0ca832c8ddc07e2c4ae139a4424c19ebe8f74ebd55ece96cbcf6c25b68902f355b680",
          "sha256": "5b6e80de1852fd1578c97e27270120aad73ac299adb4f95044e302ca138ab63e",
          "sha1": "07eeacd336f37985993d5251d34d47666e530c1a",
          "md5": "e865c2605c4d3560782e498c92e6d91b"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "xarpeg-kotlin-peg-parser-mingwx64-2.1.0-sources.jar",
          "url": "xarpeg-kotlin-peg-parser-mingwx64-2.1.0-sources.jar",
          "size": 17377,
          "sha512": "da48f24c34f6055592264ab228555d1a1205269081c9cedbfb6ffcfefe834237bb2839a334576ac08b7f41a59bfb712beda6d229243d8d464108a71560f0a471",
          "sha256": "fa1190f3efbaf80cbcce1a0fa952b1ec806812c13d84f151a03e1e62d31a1841",
          "sha1": "539c6cc91c47d379dc44d9a01a46267b017280a0",
          "md5": "5af78d8e7dd3fb7ded999b9fe2a4378d"
        }
      ]
    }
  ]
}
