{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mirrgieriana.xarpite",
    "module": "xarpeg-kotlin-peg-parser",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "xarpeg-kotlin-peg-parser-metadata-1.0.5.jar",
          "url": "xarpeg-kotlin-peg-parser-1.0.5.jar",
          "size": 15040,
          "sha512": "7d11d1f09ce8ce9b4de010bd1c36258b1d914a786c0a5449285fcd39ad8ff13664505e34569e1484fb74be8d612689f8fcc73bf59aeb8b0c9d32e70e0ac75181",
          "sha256": "a447f501fe51126f7a58eb3549beb5954ca21aae0a02d96854cbd1ec5c676d84",
          "sha1": "23cdda029d80dc8d400620ec0528681a0f72cab6",
          "md5": "0b116ef3e976234901a5471d9bb32da8"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "xarpeg-kotlin-peg-parser-kotlin-1.0.5-sources.jar",
          "url": "xarpeg-kotlin-peg-parser-1.0.5-sources.jar",
          "size": 11861,
          "sha512": "263c491633e52b23a0e88c07fd82ac7be3ee10917bd234ed5150d26ac114811e673bfc68f658d98448a56f749940175a734c20b722d41202211477caab4b1bee",
          "sha256": "17c42e651b0a64df578104b367b6c31e90bc344062cd957f2209519e9bf390a8",
          "sha1": "338b0eac8d45305a88be20caf4c3a3c181998c5c",
          "md5": "097d666d8811da727bd5d54090f67741"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../xarpeg-kotlin-peg-parser-js/1.0.5/xarpeg-kotlin-peg-parser-js-1.0.5.module",
        "group": "io.github.mirrgieriana.xarpite",
        "module": "xarpeg-kotlin-peg-parser-js",
        "version": "1.0.5"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../xarpeg-kotlin-peg-parser-js/1.0.5/xarpeg-kotlin-peg-parser-js-1.0.5.module",
        "group": "io.github.mirrgieriana.xarpite",
        "module": "xarpeg-kotlin-peg-parser-js",
        "version": "1.0.5"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../xarpeg-kotlin-peg-parser-js/1.0.5/xarpeg-kotlin-peg-parser-js-1.0.5.module",
        "group": "io.github.mirrgieriana.xarpite",
        "module": "xarpeg-kotlin-peg-parser-js",
        "version": "1.0.5"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../xarpeg-kotlin-peg-parser-jvm/1.0.5/xarpeg-kotlin-peg-parser-jvm-1.0.5.module",
        "group": "io.github.mirrgieriana.xarpite",
        "module": "xarpeg-kotlin-peg-parser-jvm",
        "version": "1.0.5"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../xarpeg-kotlin-peg-parser-jvm/1.0.5/xarpeg-kotlin-peg-parser-jvm-1.0.5.module",
        "group": "io.github.mirrgieriana.xarpite",
        "module": "xarpeg-kotlin-peg-parser-jvm",
        "version": "1.0.5"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../xarpeg-kotlin-peg-parser-jvm/1.0.5/xarpeg-kotlin-peg-parser-jvm-1.0.5.module",
        "group": "io.github.mirrgieriana.xarpite",
        "module": "xarpeg-kotlin-peg-parser-jvm",
        "version": "1.0.5"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../xarpeg-kotlin-peg-parser-linuxx64/1.0.5/xarpeg-kotlin-peg-parser-linuxx64-1.0.5.module",
        "group": "io.github.mirrgieriana.xarpite",
        "module": "xarpeg-kotlin-peg-parser-linuxx64",
        "version": "1.0.5"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../xarpeg-kotlin-peg-parser-linuxx64/1.0.5/xarpeg-kotlin-peg-parser-linuxx64-1.0.5.module",
        "group": "io.github.mirrgieriana.xarpite",
        "module": "xarpeg-kotlin-peg-parser-linuxx64",
        "version": "1.0.5"
      }
    }
  ]
}
