{
  "formatVersion": "1.1",
  "component": {
    "url": "../../xarpeg-kotlin-peg-parser/1.0.5/xarpeg-kotlin-peg-parser-1.0.5.module",
    "group": "io.github.mirrgieriana.xarpite",
    "module": "xarpeg-kotlin-peg-parser",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "xarpeg-kotlin-peg-parser-jvm-1.0.5.jar",
          "url": "xarpeg-kotlin-peg-parser-jvm-1.0.5.jar",
          "size": 62060,
          "sha512": "0a50fe9d29db824e6bfefd7595f697e678e4d0d080d47f65898bd077ecd74f4a47075309a7c09b07d74df3c777265dba1943da6b6f53121a7814eea778da3a81",
          "sha256": "a514aa18731e0462b4cd7bdf2d708b6188febb25f738421f5aeeeeb97056474f",
          "sha1": "c687db558cd27a12ae67814b86cc1673325f3ce5",
          "md5": "cd1e966ace734d9271ef42bc3f3c58f2"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "xarpeg-kotlin-peg-parser-jvm-1.0.5.jar",
          "url": "xarpeg-kotlin-peg-parser-jvm-1.0.5.jar",
          "size": 62060,
          "sha512": "0a50fe9d29db824e6bfefd7595f697e678e4d0d080d47f65898bd077ecd74f4a47075309a7c09b07d74df3c777265dba1943da6b6f53121a7814eea778da3a81",
          "sha256": "a514aa18731e0462b4cd7bdf2d708b6188febb25f738421f5aeeeeb97056474f",
          "sha1": "c687db558cd27a12ae67814b86cc1673325f3ce5",
          "md5": "cd1e966ace734d9271ef42bc3f3c58f2"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xarpeg-kotlin-peg-parser-jvm-1.0.5-sources.jar",
          "url": "xarpeg-kotlin-peg-parser-jvm-1.0.5-sources.jar",
          "size": 11861,
          "sha512": "263c491633e52b23a0e88c07fd82ac7be3ee10917bd234ed5150d26ac114811e673bfc68f658d98448a56f749940175a734c20b722d41202211477caab4b1bee",
          "sha256": "17c42e651b0a64df578104b367b6c31e90bc344062cd957f2209519e9bf390a8",
          "sha1": "338b0eac8d45305a88be20caf4c3a3c181998c5c",
          "md5": "097d666d8811da727bd5d54090f67741"
        }
      ]
    }
  ]
}
