{
  "formatVersion": "1.1",
  "component": {
    "url": "../../xarpeg-kotlin-peg-parser/3.0.0/xarpeg-kotlin-peg-parser-3.0.0.module",
    "group": "io.github.mirrgieriana.xarpite",
    "module": "xarpeg-kotlin-peg-parser",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "xarpeg-kotlin-peg-parser-linuxX64Main-3.0.0.klib",
          "url": "xarpeg-kotlin-peg-parser-linuxx64-3.0.0.klib",
          "size": 202353,
          "sha512": "16ecf09ab4000f240fba0693aff64ea8de1a64c64362853b285f96b5aeed54b9b952c2af60ce656298fa2b503af89361275fa80d4b47bef75765206a6eacbb94",
          "sha256": "9f6c8c82c7e3fc32ed95c9925e150baa2a366a906e66c5192e3b84f93af55a43",
          "sha1": "259a41359803727fd2dce818019bcbc2184dc036",
          "md5": "28023dfb1fe506d1dc27c83f92815386"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "xarpeg-kotlin-peg-parser-linuxx64-3.0.0-sources.jar",
          "url": "xarpeg-kotlin-peg-parser-linuxx64-3.0.0-sources.jar",
          "size": 19658,
          "sha512": "f91a2184e5cecb2e5f204e275b2ed8032a361e19023e261e28eb9a01e5c59d7bb84d5cccc1af6190ec36537103162cf17509f7f3070b6a44be4ac829ee96543e",
          "sha256": "206d751dda36b2bbcd4c6ca0b750d61dbbe09705d93efd060761fe8132b5400a",
          "sha1": "149b5e86a24609641711cd55beaba0947e5d2952",
          "md5": "63d1733c0cd892ff2733ee97921932fe"
        }
      ]
    }
  ]
}
