{
  "formatVersion": "1.1",
  "component": {
    "url": "../../xarpeg/5.1.0/xarpeg-5.1.0.module",
    "group": "io.github.mirrgieriana",
    "module": "xarpeg",
    "version": "5.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "xarpeg-linuxX64Main-5.1.0.klib",
          "url": "xarpeg-linuxx64-5.1.0.klib",
          "size": 213531,
          "sha512": "fa98c71a0a9556392e69411bfe57d602f9aceaec5fb44f738fa833cd82e6b9ac3dedc4871a35e28713306d295b324352f5f24610264edc0074dee7a27a0a2e23",
          "sha256": "419c77d27ac69472ea22f2eaee2fad9645bd5fa16deb1ec98df7639b3c560769",
          "sha1": "41684a669277a64db0f6b636094b8d4443e0af62",
          "md5": "cc81a193c4945e9c8f98b91a66550fa5"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "xarpeg-linuxx64-5.1.0-sources.jar",
          "url": "xarpeg-linuxx64-5.1.0-sources.jar",
          "size": 22580,
          "sha512": "0c208da5ed4fd623b38f85dfa1377360470c713ebfa19307a13d9f6402bff1ec053ad9c42f18083e680828b9ce19f92ca1dfa250a95816c9a67e536de18fcf52",
          "sha256": "ebb889831ca29791fe9995012879d80c17946eb19233d12700f2245aacc38267",
          "sha1": "f01b41622a0588cf2017a24a526a25e550df3636",
          "md5": "0b719765ad995071c57b38f5c32b8af6"
        }
      ]
    }
  ]
}
