{
  "formatVersion": "1.1",
  "component": {
    "url": "../../xarpeg/5.1.0/xarpeg-5.1.0.module",
    "group": "io.github.mirrgieriana",
    "module": "xarpeg",
    "version": "5.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "xarpeg-mingwX64Main-5.1.0.klib",
          "url": "xarpeg-mingwx64-5.1.0.klib",
          "size": 213532,
          "sha512": "d6d7392d62dd80b52109dfd7e052ddfc5e1f3c09df5f43d36134aa5e5349996c4e1b4ce3934212036f992bb2dcae9c5ebd10409485642cce42314e6e0c8282f2",
          "sha256": "82eac8ca2de90da9b5a308f866cdbab098fa5ca447f7788e869643b9b5410a98",
          "sha1": "9814303815808680566d4d4f1407ec4dc2c14e9a",
          "md5": "f7b946fa6de7e1d6ca7fa477fa3b7a8f"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "xarpeg-mingwx64-5.1.0-sources.jar",
          "url": "xarpeg-mingwx64-5.1.0-sources.jar",
          "size": 22580,
          "sha512": "0c208da5ed4fd623b38f85dfa1377360470c713ebfa19307a13d9f6402bff1ec053ad9c42f18083e680828b9ce19f92ca1dfa250a95816c9a67e536de18fcf52",
          "sha256": "ebb889831ca29791fe9995012879d80c17946eb19233d12700f2245aacc38267",
          "sha1": "f01b41622a0588cf2017a24a526a25e550df3636",
          "md5": "0b719765ad995071c57b38f5c32b8af6"
        }
      ]
    }
  ]
}
