{
  "formatVersion": "1.1",
  "component": {
    "url": "../../xarpeg-kotlinMultiplatform/4.0.2/xarpeg-kotlinMultiplatform-4.0.2.module",
    "group": "io.github.mirrgieriana",
    "module": "xarpeg-kotlinMultiplatform",
    "version": "4.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "xarpeg-kotlin-peg-parser-linuxX64Main-4.0.2.klib",
          "url": "xarpeg-linuxX64-4.0.2.klib",
          "size": 203500,
          "sha512": "fba4c3306d2fba2c85f63b4d6a403955f4b16f5d2bbab689f8c57a4d6fc3c42bece1c74c19869bda89ffc7f0ca2994ed04ff1c10f3d5305596f330d5987786dc",
          "sha256": "a4e3e6e362fbb10cbfda0bb30df30d4d6c16caa223e0d4cdde5e763bc746099d",
          "sha1": "e450e5c76b38969d0fb41b4c1fa366881b3f4701",
          "md5": "018a3c8a0a255e722d104140b605f70a"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "xarpeg-kotlin-peg-parser-linuxx64-4.0.2-sources.jar",
          "url": "xarpeg-linuxX64-4.0.2-sources.jar",
          "size": 20087,
          "sha512": "df31909ebf807945cd63cc20fbf12c02b7421c7a8182159bc9505d9395adc28c4a4f07e34bac4e3b71f537784c3fd49bc4c03a4ab01bd93c40c14c9be9290947",
          "sha256": "a8ebc99610c06ca4012e801cae9e260276a3bc925003f2e4a66ae1ad8e917621",
          "sha1": "06ee316395739605dd5d5cb8e420c2c5dc7d0f93",
          "md5": "8ca18ca33f07e8c9ec509558d7ed37da"
        }
      ]
    }
  ]
}
