{
  "formatVersion": "1.1",
  "component": {
    "url": "../../xarpeg/5.1.0/xarpeg-5.1.0.module",
    "group": "io.github.mirrgieriana",
    "module": "xarpeg",
    "version": "5.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "xarpeg-js-5.1.0.klib",
          "url": "xarpeg-js-5.1.0.klib",
          "size": 211334,
          "sha512": "b523356482c7754918b81d2bd34cbe31d70c14027a9a6344de635d50d62248f6819008d17b3394c9c84166bf38a9db528b14c3b2e0893b86b5d6c2576289931e",
          "sha256": "c4baad706669282545c42bbce329857b252421a73c57e0f556e7a7a15c033190",
          "sha1": "e5f8df2647015c853884d73741a83956d0ce4ba1",
          "md5": "63c23b9efa5b4f5e782d93074be52d5b"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "xarpeg-js-5.1.0.klib",
          "url": "xarpeg-js-5.1.0.klib",
          "size": 211334,
          "sha512": "b523356482c7754918b81d2bd34cbe31d70c14027a9a6344de635d50d62248f6819008d17b3394c9c84166bf38a9db528b14c3b2e0893b86b5d6c2576289931e",
          "sha256": "c4baad706669282545c42bbce329857b252421a73c57e0f556e7a7a15c033190",
          "sha1": "e5f8df2647015c853884d73741a83956d0ce4ba1",
          "md5": "63c23b9efa5b4f5e782d93074be52d5b"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "xarpeg-js-5.1.0-sources.jar",
          "url": "xarpeg-js-5.1.0-sources.jar",
          "size": 22533,
          "sha512": "8d6e92599104a6c95d90513836d8086ccd34397f2b4291df396922ce041ba43ec46f639ed044f9d172a04bfb015b3e50b8bbaf881ba13d72bc324dc251072f4b",
          "sha256": "93d94fb66b511490d00fe4af21b89231afd702d283abebdf38d88b52691d76aa",
          "sha1": "32fa90310802d94b4d0092147ffa90ac5e1a2629",
          "md5": "5abf9a862b0183096211bcdc0556e2c8"
        }
      ]
    }
  ]
}
