{
  "formatVersion": "1.1",
  "component": {
    "url": "../../xarpeg-kotlinMultiplatform/4.0.3/xarpeg-kotlinMultiplatform-4.0.3.module",
    "group": "io.github.mirrgieriana",
    "module": "xarpeg-kotlinMultiplatform",
    "version": "4.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "xarpeg-kotlin-peg-parser-js-4.0.3.klib",
          "url": "xarpeg-js-4.0.3.klib",
          "size": 203682,
          "sha512": "86a499d9d4f9bb6ffe0fb1d2aa110929c90a3d3f359296e6801d699346c73d3f83dddf72badd869aa041f1b9d89b70738e8ae8639543a64d0eb78c40cc5e89fc",
          "sha256": "595c75495052e8f05df07da592c93e908e11d191337823c093e4ab97fbbb9042",
          "sha1": "cf3ef58e9b81b77a660e6e61ada65098a9d8b31c",
          "md5": "16b2664f8af51d7ca69e5c0cd260558e"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "xarpeg-kotlin-peg-parser-js-4.0.3.klib",
          "url": "xarpeg-js-4.0.3.klib",
          "size": 203682,
          "sha512": "86a499d9d4f9bb6ffe0fb1d2aa110929c90a3d3f359296e6801d699346c73d3f83dddf72badd869aa041f1b9d89b70738e8ae8639543a64d0eb78c40cc5e89fc",
          "sha256": "595c75495052e8f05df07da592c93e908e11d191337823c093e4ab97fbbb9042",
          "sha1": "cf3ef58e9b81b77a660e6e61ada65098a9d8b31c",
          "md5": "16b2664f8af51d7ca69e5c0cd260558e"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "xarpeg-kotlin-peg-parser-js-4.0.3-sources.jar",
          "url": "xarpeg-js-4.0.3-sources.jar",
          "size": 20031,
          "sha512": "078a66aa832163c1eb049a40346a1bce26d172893418c2f8f01292b754692db8cb57a41d0463218b9b3f70eaeab0c7c22a8b6f9d074ac1866ebbcf31338bd655",
          "sha256": "27c12d2387b221248e24b396a78b72000942df00cd7c9aa477004e04aa223518",
          "sha1": "e93402d991ae217f61648c9969b7105727464a11",
          "md5": "b1b24f2002ccabbf617742c6b9a4dbc6"
        }
      ]
    }
  ]
}
