{
  "formatVersion": "1.1",
  "component": {
    "url": "../../xarpeg-kotlin-peg-parser/3.0.0/xarpeg-kotlin-peg-parser-3.0.0.module",
    "group": "io.github.mirrgieriana.xarpite",
    "module": "xarpeg-kotlin-peg-parser",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "xarpeg-kotlin-peg-parser-linuxArm64Main-3.0.0.klib",
          "url": "xarpeg-kotlin-peg-parser-linuxarm64-3.0.0.klib",
          "size": 202365,
          "sha512": "f0747536cfeca8fdef5248b5ca047e6ddee295204bb9cad4c6e5bb44e2e2773e57c6b8b9f6f3138f0ceb3f096a037cbdabb83d65a19c946441be50ef747facb5",
          "sha256": "8ce92f42fdd6aa9cb38d8826b4f33f9f73b69f2be76d04d0b92a9dd841983ee6",
          "sha1": "8cbfa82846bc8f713166843173c60aa60b78c8c4",
          "md5": "a4f53af2106888dd90e23d6290a5cab4"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "xarpeg-kotlin-peg-parser-linuxarm64-3.0.0-sources.jar",
          "url": "xarpeg-kotlin-peg-parser-linuxarm64-3.0.0-sources.jar",
          "size": 19658,
          "sha512": "f91a2184e5cecb2e5f204e275b2ed8032a361e19023e261e28eb9a01e5c59d7bb84d5cccc1af6190ec36537103162cf17509f7f3070b6a44be4ac829ee96543e",
          "sha256": "206d751dda36b2bbcd4c6ca0b750d61dbbe09705d93efd060761fe8132b5400a",
          "sha1": "149b5e86a24609641711cd55beaba0947e5d2952",
          "md5": "63d1733c0cd892ff2733ee97921932fe"
        }
      ]
    }
  ]
}
