{
  "formatVersion": "1.1",
  "component": {
    "url": "../../xarpeg-kotlinMultiplatform/4.0.2/xarpeg-kotlinMultiplatform-4.0.2.module",
    "group": "io.github.mirrgieriana",
    "module": "xarpeg-kotlinMultiplatform",
    "version": "4.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "xarpeg-kotlin-peg-parser-mingwX64Main-4.0.2.klib",
          "url": "xarpeg-mingwX64-4.0.2.klib",
          "size": 203502,
          "sha512": "2a6a77718fb7c004f82ade26c76a178b5ed44d8da2bffdf458ef52a471eefd471abcf613430f9004e64e823cef738a22fa5b0013e3b233462952293698ee0e1d",
          "sha256": "ed0a378bcebc7d32b69f5a906a819bd9724a526299611ca5c3c426ce314be08b",
          "sha1": "38d503a10dd9c400fe0bdc836e3d4e94accf89bd",
          "md5": "549354f8072f1c0ccc3c3075dd13036d"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "xarpeg-kotlin-peg-parser-mingwx64-4.0.2-sources.jar",
          "url": "xarpeg-mingwX64-4.0.2-sources.jar",
          "size": 20087,
          "sha512": "df31909ebf807945cd63cc20fbf12c02b7421c7a8182159bc9505d9395adc28c4a4f07e34bac4e3b71f537784c3fd49bc4c03a4ab01bd93c40c14c9be9290947",
          "sha256": "a8ebc99610c06ca4012e801cae9e260276a3bc925003f2e4a66ae1ad8e917621",
          "sha1": "06ee316395739605dd5d5cb8e420c2c5dc7d0f93",
          "md5": "8ca18ca33f07e8c9ec509558d7ed37da"
        }
      ]
    }
  ]
}
