{
  "formatVersion": "1.1",
  "component": {
    "url": "../../xarpeg-kotlin-peg-parser/1.0.5/xarpeg-kotlin-peg-parser-1.0.5.module",
    "group": "io.github.mirrgieriana.xarpite",
    "module": "xarpeg-kotlin-peg-parser",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "xarpeg-kotlin-peg-parser-js-1.0.5.klib",
          "url": "xarpeg-kotlin-peg-parser-js-1.0.5.klib",
          "size": 66462,
          "sha512": "280876a8bcd57021a1874809c742e226fa4589c6236a30ad60a24514df729f350d7b945187877eaa5071ce4334595f4d7e452b19f2dec21b55011c770701a044",
          "sha256": "e7c1e6ebf3a44ca1d29ab080bca3c9e8a5bff7668d250b876992eee71845f746",
          "sha1": "97e1b76a626055924c227f582390cef17a20fa62",
          "md5": "29ec79778cc57c5ff2cf4e0539dda1f5"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "xarpeg-kotlin-peg-parser-js-1.0.5.klib",
          "url": "xarpeg-kotlin-peg-parser-js-1.0.5.klib",
          "size": 66462,
          "sha512": "280876a8bcd57021a1874809c742e226fa4589c6236a30ad60a24514df729f350d7b945187877eaa5071ce4334595f4d7e452b19f2dec21b55011c770701a044",
          "sha256": "e7c1e6ebf3a44ca1d29ab080bca3c9e8a5bff7668d250b876992eee71845f746",
          "sha1": "97e1b76a626055924c227f582390cef17a20fa62",
          "md5": "29ec79778cc57c5ff2cf4e0539dda1f5"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "xarpeg-kotlin-peg-parser-js-1.0.5-sources.jar",
          "url": "xarpeg-kotlin-peg-parser-js-1.0.5-sources.jar",
          "size": 11861,
          "sha512": "263c491633e52b23a0e88c07fd82ac7be3ee10917bd234ed5150d26ac114811e673bfc68f658d98448a56f749940175a734c20b722d41202211477caab4b1bee",
          "sha256": "17c42e651b0a64df578104b367b6c31e90bc344062cd957f2209519e9bf390a8",
          "sha1": "338b0eac8d45305a88be20caf4c3a3c181998c5c",
          "md5": "097d666d8811da727bd5d54090f67741"
        }
      ]
    }
  ]
}
