{
  "formatVersion": "1.1",
  "component": {
    "url": "../../xarpeg/5.0.0/xarpeg-5.0.0.module",
    "group": "io.github.mirrgieriana",
    "module": "xarpeg",
    "version": "5.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "xarpeg-linuxX64Main-5.0.0.klib",
          "url": "xarpeg-linuxx64-5.0.0.klib",
          "size": 202342,
          "sha512": "65aa6abc47918b8ec7d8073bd56ae12a44980168df78075700475c7828f3c2f7ac9eb0eca2926d1a78022f427a2ea326a568d79f622740b9c8685a613bf4478e",
          "sha256": "9100163ccca2d86e987785f81bfa7c01a49cdd7b3d8900c042bd2ce1cf8edbbd",
          "sha1": "a43a90bb229ad944b6c9d375d2a98a4461e31f94",
          "md5": "bfd940dbb9682e05e28c4e2fe476c388"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "xarpeg-linuxx64-5.0.0-sources.jar",
          "url": "xarpeg-linuxx64-5.0.0-sources.jar",
          "size": 19145,
          "sha512": "5be88890f548e647ead35b1b3f65100e212b49b47105ea18ca96c49c826d7c920f81e7e7f9af0c3d0cbc2430b050d758e0d0b736074f211c47f4f53cce6096d2",
          "sha256": "f6745cc1c1b1b61d5e32dfa5cdfeee967eb451cc11fb824d9fb3245331e154c9",
          "sha1": "b4a6d89c1a9dc825c5bc15ac3198d37b4073e2fc",
          "md5": "b194fa6cf86b34f6326593bdb342ad2d"
        }
      ]
    }
  ]
}
