{
  "formatVersion": "1.1",
  "component": {
    "url": "../../xarpeg-kotlin-peg-parser/2.1.0/xarpeg-kotlin-peg-parser-2.1.0.module",
    "group": "io.github.mirrgieriana.xarpite",
    "module": "xarpeg-kotlin-peg-parser",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "xarpeg-kotlin-peg-parser-wasm-js-2.1.0.klib",
          "url": "xarpeg-kotlin-peg-parser-wasm-js-2.1.0.klib",
          "size": 191744,
          "sha512": "42d74983a011a383ceddfe117a933aa53fae7b1c3207737ff337ca208ad5a092f166f545d640be64433848b4a81e5f52229187643d160f069c468d0695283976",
          "sha256": "8d59341cfe6449b38fd4f33cc8709ed03c05f6091c31e7223299335028886aac",
          "sha1": "27233901174d8309c34fd53dc3439dfcf4243639",
          "md5": "280f92641a872beae9bccb888d4e3b55"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "xarpeg-kotlin-peg-parser-wasm-js-2.1.0.klib",
          "url": "xarpeg-kotlin-peg-parser-wasm-js-2.1.0.klib",
          "size": 191744,
          "sha512": "42d74983a011a383ceddfe117a933aa53fae7b1c3207737ff337ca208ad5a092f166f545d640be64433848b4a81e5f52229187643d160f069c468d0695283976",
          "sha256": "8d59341cfe6449b38fd4f33cc8709ed03c05f6091c31e7223299335028886aac",
          "sha1": "27233901174d8309c34fd53dc3439dfcf4243639",
          "md5": "280f92641a872beae9bccb888d4e3b55"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "xarpeg-kotlin-peg-parser-wasm-js-2.1.0-sources.jar",
          "url": "xarpeg-kotlin-peg-parser-wasm-js-2.1.0-sources.jar",
          "size": 17377,
          "sha512": "8a51b43b28d2b42181dbeae2d42b775d254fe5f8cd75491c109994cf8637a5577cdb91fe758dbc319ea2c43ec3416149da743cb82c908a1e14026b782f4f3874",
          "sha256": "1a6fbb7c0015f75f23e004e17465fea7f434f50778452b60e7e4890a626490aa",
          "sha1": "5e39f5ac1869d6c4a2bf60818f58d346e72b5623",
          "md5": "7c606d1c42759ce36d4be8917a30ec38"
        }
      ]
    }
  ]
}
