{
  "formatVersion": "1.1",
  "component": {
    "url": "../../xarpeg-kotlin-peg-parser/2.1.0/xarpeg-kotlin-peg-parser-2.1.0.module",
    "group": "io.github.mirrgieriana.xarpite",
    "module": "xarpeg-kotlin-peg-parser",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "xarpeg-kotlin-peg-parser-jvm-2.1.0.jar",
          "url": "xarpeg-kotlin-peg-parser-jvm-2.1.0.jar",
          "size": 113186,
          "sha512": "7b56e9e962b80463788edbb98f65d5e1b766f4c5049b013f3ef7b35929e432237c9c746ef54e4396efc30818f61c46e81f830e735bb7fdb24b0222a5bd9a4ca6",
          "sha256": "019e7c60646662199c258a4a458f08e8eea969e3fb94399a233d564cf9d69eb8",
          "sha1": "1b5d6a4f91366164292de8e9c330ee987faf98ac",
          "md5": "63b1cccc811676dc427591d859b63fed"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "xarpeg-kotlin-peg-parser-jvm-2.1.0.jar",
          "url": "xarpeg-kotlin-peg-parser-jvm-2.1.0.jar",
          "size": 113186,
          "sha512": "7b56e9e962b80463788edbb98f65d5e1b766f4c5049b013f3ef7b35929e432237c9c746ef54e4396efc30818f61c46e81f830e735bb7fdb24b0222a5bd9a4ca6",
          "sha256": "019e7c60646662199c258a4a458f08e8eea969e3fb94399a233d564cf9d69eb8",
          "sha1": "1b5d6a4f91366164292de8e9c330ee987faf98ac",
          "md5": "63b1cccc811676dc427591d859b63fed"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "xarpeg-kotlin-peg-parser-jvm-2.1.0-sources.jar",
          "url": "xarpeg-kotlin-peg-parser-jvm-2.1.0-sources.jar",
          "size": 17335,
          "sha512": "c103d90fde070dcffcbb70c7c374f40b07d15038742d194b361781ab6d9225c3973f2aa767c12b70c056d4b15d6b78784d32595f38d9e8fe72e423626bae88ac",
          "sha256": "4da06cab2d24a2f0462a643d05c73ab47350eebf9adb706a4c29ebeb411c58ea",
          "sha1": "a81664dac97ed7c28e32c2d67caa617208b3b070",
          "md5": "992c22e7448857ec1d432c60d5e72082"
        }
      ]
    }
  ]
}
