{
  "formatVersion": "1.1",
  "component": {
    "url": "../../xarpeg/5.1.0/xarpeg-5.1.0.module",
    "group": "io.github.mirrgieriana",
    "module": "xarpeg",
    "version": "5.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "xarpeg-wasm-js-5.1.0.klib",
          "url": "xarpeg-wasm-js-5.1.0.klib",
          "size": 211330,
          "sha512": "916b79786e5cf7cf5d85ee22625e091c4bb5dda6eae0b22fa0708c3b501a9c7128232ca496edfa03235cdcf68d09201798f68d02590dfbe3e768b0da5e238d5c",
          "sha256": "cdf65f4c4b3e422d48df801ee6519d48ca505add355fa823f1eea1ad6585f471",
          "sha1": "daa03a905725ab773274f221ac2072eb55e6e9e2",
          "md5": "11840dd800c0afaa59e44c6d1c84fa50"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "xarpeg-wasm-js-5.1.0.klib",
          "url": "xarpeg-wasm-js-5.1.0.klib",
          "size": 211330,
          "sha512": "916b79786e5cf7cf5d85ee22625e091c4bb5dda6eae0b22fa0708c3b501a9c7128232ca496edfa03235cdcf68d09201798f68d02590dfbe3e768b0da5e238d5c",
          "sha256": "cdf65f4c4b3e422d48df801ee6519d48ca505add355fa823f1eea1ad6585f471",
          "sha1": "daa03a905725ab773274f221ac2072eb55e6e9e2",
          "md5": "11840dd800c0afaa59e44c6d1c84fa50"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "xarpeg-wasm-js-5.1.0-sources.jar",
          "url": "xarpeg-wasm-js-5.1.0-sources.jar",
          "size": 22581,
          "sha512": "f431e8e4d07d2933efa65cbaabde265d9cd5fb609431a37a39c3951378cab2a4f16b23c0869bfe3942345e3e61779772ed9c2cba29d9e85321d6e13b84713f44",
          "sha256": "b3268d569daf11d050c2c2984939d9fd72121674eb3987a7783448d44acc0f2c",
          "sha1": "2fe32857b456a63a0e019ddf0bc61a68e516d852",
          "md5": "824296c2e447012f74576230e200830a"
        }
      ]
    }
  ]
}
