{
  "formatVersion": "1.1",
  "component": {
    "url": "../../xarpeg-kotlin-peg-parser/2.0.0/xarpeg-kotlin-peg-parser-2.0.0.module",
    "group": "io.github.mirrgieriana.xarpite",
    "module": "xarpeg-kotlin-peg-parser",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "xarpeg-kotlin-peg-parser-js-2.0.0.klib",
          "url": "xarpeg-kotlin-peg-parser-js-2.0.0.klib",
          "size": 191755,
          "sha512": "f020c51a134d45da7b5865af6d3bbe29ccdb0314c6d8b143813ee3f48e0b265e9923a6bb9258494ca07edd4ce0cf652acf49ea37012282d8c245b53d631e33f7",
          "sha256": "5d6f7ecc6aa7c862989e36a776a1ee57bc1eaa69421dc950ecede9572fa8db75",
          "sha1": "f6ff7df8e176363b8b427364f05b1055d68a3cdc",
          "md5": "0ecebc1a9604aeab12022c6edd7a5fcf"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.2.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "xarpeg-kotlin-peg-parser-js-2.0.0.klib",
          "url": "xarpeg-kotlin-peg-parser-js-2.0.0.klib",
          "size": 191755,
          "sha512": "f020c51a134d45da7b5865af6d3bbe29ccdb0314c6d8b143813ee3f48e0b265e9923a6bb9258494ca07edd4ce0cf652acf49ea37012282d8c245b53d631e33f7",
          "sha256": "5d6f7ecc6aa7c862989e36a776a1ee57bc1eaa69421dc950ecede9572fa8db75",
          "sha1": "f6ff7df8e176363b8b427364f05b1055d68a3cdc",
          "md5": "0ecebc1a9604aeab12022c6edd7a5fcf"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "xarpeg-kotlin-peg-parser-js-2.0.0-sources.jar",
          "url": "xarpeg-kotlin-peg-parser-js-2.0.0-sources.jar",
          "size": 17321,
          "sha512": "5337e1af358754db60e9f942dd25d7562fbc48c4efaf05e073f3a03ced17451a0fec9bc4b589ac8db5112dce608840e54ac496cc6611b22bf60e1e70c20b1fa2",
          "sha256": "c0910990f95ed76268192f09ec9dc156f58fa0ae2d265994104790095cb2a6de",
          "sha1": "69d4665c81b3ff74d8220664bb0ad42eb1d65ad6",
          "md5": "cfd61d3528695c0862d5485369062b36"
        }
      ]
    }
  ]
}
